### ISSUE TITLE
Audit Timing - Track use case and its steps execution time

### ISSUE THREAD

**Issue by jhomarolo** [herbsjs/buchu#13]
Following the list of features to be implemented, I came across this one and I wanted to discuss with you how you plan on doing this.

I was looking at some things and I came across this package: https://www.npmjs.com/package/execution-time

I was thinking of implementing something similar (and not implementing this direct dependency) where he would insert the execution time of each step in an array and insert it in the audit array, at the exact moment he inserted the step.

Like this, in step.js file:

```javascript

 //start count time
let ret = await step.run()
//finish count time
step.auditTrail.time = elapsedTime
this._auditTrail.steps.push(step.auditTrail)

```

**Comment by dalssoft** [comment]
great!

regarding the dependency, it seems the original code is pretty simple [1], so I don't see the need to a external lib

[1] https://github.com/svenkatreddy/execution-time/blob/master/index.js

**Comment by jhomarolo** [comment]
I analyzed the code and it seems to be very simple, despite having an internal _"pretty-hrtime"_ dependency that is not that simple but it would be possible to import it too.

If everyone agrees I will continue with the implementation of this functionality absorbing the two dependencies.

**Comment by dalssoft** [comment]
`pretty-hrtime` is a lib which formats date. I don't think we should format the date or do any "visualization" inside herbs. we should just calc the time lapse between the execution and expose it in milisecond

**Comment by jhomarolo** [comment]
Understood, I will work on this functionality and share the development of this with you.
