### ISSUE TITLE
XSS Protection

### ISSUE THREAD

**Issue by jhomarolo** [herbsjs/buchu#21]
I wonder if it makes sense to add xss protection (Cross-site scripting) to usecase requests to this lib.

Example of code in main.js inside examples folder:

```
   void async function main() {
    const user = { user: "John", id: '923b8b9a', isAdmin: true, name: (function(){console.log('This lib is vulnerable')}()) 
    }

    const req = {
        listId: 1,
        item: { id: 10, name: "Do not forget this", position: 9 }
    }

    const uc = addOrUpdateItem()
    uc.authorize(user)
    await uc.run(req)


}()
```

**Result after run: This lib is vulnerable**

Do you believe it makes sense add this feature here or somewhere else, like herbs2gql?

**Comment by endersoncosta** [comment]
I believe that the best location to implement the protections is on threshold layers, entrance or exit... But in this case, maybe an implementation of a function prevent is a good choice too...

We can use functions sometime as parameter, then remove this feature isn't a good choice, but remove the auto-execute and force the declaration is the best way in my vision...

**Comment by jhomarolo** [comment]
I thought about the possibility of putting it in a more external layer, of infrastructure, as a middleware or functionality in the API's, but because it is something serious, I decided to open this discussion, because I believe that there may be a series of functionalities in the security area that may arise.

**Comment by italojsv** [comment]
We can use the helmet in our presentation(API) layer as a middleware, they prevent about xss and another common attack too
https://helmetjs.github.io/

**Comment by jhomarolo** [comment]
Does the helmet support applications that do not use express? I had ruled out something like that, because we have applications that don't use express.

**Comment by dalssoft** [comment]
A few extra info to enhance this discussion. 

Buchu / Herbs is a application layer not a infrastructure layer. 

onion architecture:
[ infra [application] infra ]

That said:

(1) how would a JS function be (realistic) be inputted by a controller / resolver into a use case?

 > `name: (function(){console.log('This lib is vulnerable')}()) `

If (big if) it is possible a type check should solve it, right? `function` != `String`

(2) `helmet` belongs to the infrastructure layer along with `express`. `helmet` and `express` deal with http, dns, etc. where Buchu deals with business logic and input/output interfaces. Also a `express` controller (or a graphql resolver) is the layer calling `herbs` so `herbs` should have no knowledge about the caller / infra layer.

**Comment by italojsv** [comment]
We have helmet for many technologies, just check the complete list [here](https://helmetjs.github.io/see-also/)
- [koa](https://github.com/venables/koa-helmet)
- [fastify](https://github.com/fastify/fastify-helmet)

**Comment by jhomarolo** [comment]
One possibility would be use the extension apollo-server-express to use helmet.

Like here: https://atheros.ai/blog/graphql-security-in-node-js-project

My initial question was more in the scope of asking ourselves if we should be concerned with application security in the library or if we would leave that to other layers or inside some glue library.

**Comment by dalssoft** [comment]
> We have helmet for many technologies, just check the complete list [here](https://helmetjs.github.io/see-also/)
> 
>     * [koa](https://github.com/venables/koa-helmet)
> 
>     * [fastify](https://github.com/fastify/fastify-helmet)

it just reinforces my argument. both koa and fastify are infrastructure libraries which deal with protocols and controllers

Herbsjs has no intention to substitute or compete with these libraries

**Comment by dalssoft** [comment]
> My initial question was more in the scope of asking ourselves if we should be concerned with application security in the library or if we would leave that to other layers or inside some glue library

Great point. I think we should be worried only if the previous layer (like a controller or a resolver) is lenient in some cases and the attack is possible inside a UC or Entity.
