### ISSUE TITLE
Implement "Stop" return type

### ISSUE THREAD

**Issue by BritoDoug** [herbsjs/buchu#26]
This issue consist in the necessity to Stop the UC sequence execution in the scenario where, gived some condicion I need to return a satisfactory response, and not a Err, and Stop execution of the remanacent steps

I propose something like a: 
```js
Stop(), End() or Ok().final()
```
 open to suggestions

**Comment by dalssoft** [comment]
To bring more info to this thread lets start with some background:

`Ok` and `Err` are based on `result` from rust [1]

> `Result<T, E>` is the type used for returning and propagating errors. It is an enum with the variants, `Ok(T)`, representing success and containing a value, and `Err(E)`, representing error and containing an error value.

So `Ok` and `Err` are not part of a use case or step flow. It is a general way to return values and errors avoiding (1) return nulls [2] and (2) throwing exceptions (using `Err` instead).

It is so separated from buchu that I thought to give it its own package many times (and I still think we should do it).

Giving that I think the problem you bring is legit so I would like to explore possible solutions.

Could you provide a code showing when it happens?

[1] https://doc.rust-lang.org/std/result/
[2] https://refactoring.guru/pt-br/introduce-null-object

**Comment by m7vicente** [comment]
I can think in some cases that scenario occurs.

Let's use and fictitious scenario on To do List that could be implemented:
If before added a new item on list,  a step of `ifElse` to check if the list doesn't have been added before. To end the execution currently, is necessary to return Err() to interrupt the usecase, If the user is expecting the full list as return of usecase, its necessery to pass the list an Err() and check in the resolver if the result is an actual error or a success but not necessary to follow all steps.

Implementing something like `Stop(Ok(list))` we can easily make this case simple, once just check if the return is `ucResult.isOk` or error,  make unnecessary any other verification on controller or resolvers to get usecase result.

Another idea to implement, can be just to remove Ok() to follow the next step, and implement a Continue(), since Ok() is a result type they could make like Err() and finish the execution but return the expected result from usecase.

**Comment by dalssoft** [comment]
brainstorm...

whats if instead of:

```js
return Ok()
```

something like:
```js
return ctx.Stop()
```
or 
```js
return step.Stop()  // this looks nicer
```

?

The idea here is not to change the current `Ok` / `Err` behavior but to add specific flow control to Buchu

**Comment by m7vicente** [comment]
I really like return `step.Stop()`

`return usecase.Stop()`  sounds right too, but since usecase is a function maybe it doesn't make sense to return this new function in usecase return object.

What about just create a type to import called `return Stop()` or  maybe `return Stopped()`?

**Comment by endersoncosta** [comment]
Ok.end() or Ok.finally() sounds good to me, because the behavior is Ok, with a flag that defines the break of the flow...

**Comment by BritoDoug** [comment]
I don't have any problem in create a new flow control and keep Ok/Err untouch, but I think `step.Stop()` sounds like the step end, and not the entire UC. I personally prefer a approach like @m7vicente propose.

**Comment by dalssoft** [comment]
@endersoncosta check this comment - https://github.com/herbsjs/buchu/issues/26#issuecomment-767188907

@BritoDoug @m7vicente to me the solution is:

```step.Stop()``` which:
- tells/signals the step to stop the flow
- is a `Stop` return for the audit trail
- is an `Ok` return for the UC consumer (doesn't make any sense to return a `Stop`)

Nice to have: For the sake of completeness we could also have ```step.Ok()``` (alias for `Ok()`) and ```step.Err()``` (alias for `Err()`)

**Comment by dalssoft** [comment]
> 
> 
> I don't have any problem in create a new flow control and keep Ok/Err untouch, but I think `step.Stop()` sounds like the step end, and not the entire UC. I personally prefer a approach like @m7vicente propose.

@BritoDoug is there a place where stopping the step wouldn't stop the UC? If so, we could have both. `step.Stop()` to stop the step and `usecase.Stop()` to stop the UC flow. Otherwise `step.Stop()` should be enough.

**Comment by BritoDoug** [comment]
@dalssoft,  UC with multiple steps and no way to stop in a inicial conditional  was my main pain. About `step.stop()`, `Ok()` already do that, at least we use `Ok()` with that behavior.

A question, when you say to use `step.stop()` we are talk about the “buchu step” ?

**Comment by endersoncosta** [comment]
I believe that `ctx.Stop ()` is the best choice, since it encompasses the end of context as a whole...

**Comment by endersoncosta** [comment]
Because of the `nested steps` this will end totally the process of the use case, independent of the current step...

**Comment by dalssoft** [comment]
I think @endersoncosta has a point. 
Calling `ctx.stop()` would stop at the current step it was called and with that you can still return `Ok` or `Err`. Which means that we would separate the the control flow (ex: stop UC) from the return of a step or UC.

ex:
```js
'Check if it is valid list': step(ctx =>
    if (ctx.list.isValid()) {
        return Ok()
    } else {
        ctx.stop()
        return Err(ctx.list.errors)
    }
),
```

**Comment by jhomarolo** [comment]
I believe that the main gain of the stop should be to break the cycle of nested use cases completely

**Comment by dalssoft** [comment]
I believe we have stressed many scenarios. In order to move forward please bring your final thoughts to start an implementation.

**Comment by BritoDoug** [comment]
I don't see why not use `ctx.stop()` implantation, from my point of view this solution attempt the primary demand and do not interfere with `Ok` and `Err` behavior.

**Comment by endersoncosta** [comment]
why not use something like `Ok.final( message )` or `Ok.end()`, with this we can manage to the usecase ignore all other steps and return Ok...

The audit can show something like ignored to the others usecases...

**Comment by endersoncosta** [comment]
I believe that we can close this issue...
