### ISSUE TITLE
An use case can be executed twice or simultaneous sharing the same instance context

### ISSUE THREAD

**Issue by m7vicente** [herbsjs/buchu#31]
When a usecase instance built, when implementing a default resolver, the usecase object does not clean instance the context and shares information between requests.

In the `to-do list` example of Default Resolver, the usecase is required and configured in query or mutations but, in import they execute usecase function before passing for default resolver, making all requisitions run in the same instance.

To prevent this happen in the future, a status variable like “hasExcute” should be implemented, to not allow the same usecase object instance to execute twice, and change the example of `to-do list` to just execute the usecase in the default resolver function.

**Comment by dalssoft** [comment]
Not really fixed but at least won't be possible to run a use case more than one. This should avoid major bugs.

Buchu: https://github.com/herbsjs/buchu/commit/c47543679d6a2d52688443129d8d2d80b98a1883

herbs2gql: https://github.com/herbsjs/herbs2gql/commit/f2866ad65a7dbf2ead05c5686b4c6ef412530c37

Todo list updated: https://github.com/herbsjs/todolist-on-herbs/commit/6be279c5f02fa7202bd4e133b27d43d474a26346

Please, check.

**Comment by BritoDoug** [comment]
I believe that avoid the major problem, upgrade to that version of buchu is a good idea to other projects too.

**Comment by jhomarolo** [comment]
With this correction, we need to evaluate how we are going to do with the cases of recursion.

I will perform some tests and return to you.

**Comment by dalssoft** [comment]
@jhomarolo It shouldn't be a problem if for each call inside a recursion it creates a new instance.

**Comment by BritoDoug** [comment]
we can close this issue or consider @dalssoft change has been a palliative ? I believe that issue can be closed and if is the case we open another one.
