### ISSUE TITLE
Async Authorize

### ISSUE THREAD

**Issue by maikvortx** [herbsjs/buchu#34]
**Describe the solution you'd like**
When we implement the Authozire step, we must currently implement the `sync` methods, but in this step for complex validations, we need to use the` async` method to call http services or database requests.

Thus, I believe that the Step Authorize can accept `sync \ async` types of methods.

**Additional context**

![image](https://user-images.githubusercontent.com/65735194/118346767-0737c180-b514-11eb-8167-8fcc886523d7.png)

**Comment by dalssoft** [comment]
I agree. However, would be great if there was a way to not break the ecosystem.

**Comment by maikmb** [comment]
What do you mean by breaking the ecosystem? Can you give me some examples? With this implementation the usecase continues executing fine.

**Comment by dalssoft** [comment]
> What do you mean by breaking the ecosystem? 

Proposed change is a breaking change since in order to work properly one must include `await` before calling `uc.authorize()`.

The problem is there are many productions systems and glues using the sync version.
