### ISSUE TITLE
Entity schema to Request schema

### ISSUE THREAD

**Issue by dalssoft** [herbsjs/buchu#53]
It should have an easy way to transform a entity into a request schema. 

Also, it should be possible to remove or add fields for the request. For instance, removing IDs from a entity in a `create` use case.

```js
const { usecase, request } = require('buchu')
const { entity, field } = require('gotu')

const Item =
    entity('Item', {
        id: field(Number),
        description: field(String),
        isDone: field(Boolean)
    })

const createItem = usecase('Create Item', {
    
    // request: { description: String, isDone: Boolean },

    request: request.from(Item, { includeIDs: false }),
})
```

**Comment by italojs** [comment]
the discussion for this implementation is inside gotu https://github.com/herbsjs/gotu/issues/49

**Comment by jhomarolo** [comment]
@italojs I don't think this idea here is the same at https://github.com/herbsjs/gotu/issues/49.

Here is transform an entity to request, choosing with the field I want to transform. There is about to omit some fields in any scenario (request or not).

Of course, is correlated, but I don't see it as the same goal. What do you think?

**Comment by jhomarolo** [comment]
@italojs In my view, we are still talking about different things. Fully correlated, but not equal.

In **gotu** we are talking about omitting fields from the entity.
In **buchu**, we are talking about choosing which fields I want in the request from an entity.

Of course, we can use both approaches to get to a similar place, but it's still not the same thing.

Terms in buchu a place to choose the fields would be very good, but if I need to omit fields from the entity in another scenario besides the request, only the gotu functionality will solve it.

For this reason, I reiterate that for me, both initiatives are valid and for me, they should both be implemented.

**Comment by dalssoft** [comment]
I agree with @jhomarolo that they are different issues for different use cases.

https://github.com/herbsjs/gotu/issues/49 is for "runtime" validation, when the entity is being used on a `usecase`/`step` and need to avoid certain fields for validation.

This https://github.com/herbsjs/buchu/issues/53 is for "build time", when it is necessary to extract the entity's metadata and convert it to a `request` object for `usecase`.

Completely different problems. That is why I'm opening the issue again.

**Comment by dalssoft** [comment]
Regarding https://github.com/herbsjs/buchu/issues/53, for me the best approach so far for this is still:

```js
request: request.from(Item, { ignoreIDs: true }),
```

there could be other approaches, like:

```js
request: request.from(Item, { ignore: ['createdAt'] }),
```

**Comment by italojs** [comment]
I think if we add this feature into gotu, we could to reuse it here

``` js
request: Item.avoid( { fields: ['createdAt'], id: true })
```

If we implement it into gotu, we will resolve the https://github.com/herbsjs/gotu/issues/49 issue and at the same time will fix this issue too

**Comment by dalssoft** [comment]
@italojs pls check my comments at https://github.com/herbsjs/buchu/issues/53#issuecomment-1100679235 

> if we add this feature into gotu

The `request:` is a use case structure. Again, `gotu` (entities) should not have any knowledge about `buchu` (use case) and its structure/etc in order to respect dependency hierarchic. In order to respect the correct order, I suggested this: https://github.com/herbsjs/buchu/issues/53#issuecomment-1100679235

**Comment by VictorTBX** [comment]
I will work on this issue

**Comment by VictorTBX** [comment]
@dalssoft 
Just to confirm: is this the expected feature?

![image](https://user-images.githubusercontent.com/4419301/173460536-59b9b299-eea5-4696-9b85-0c5960953940.png)

Should I create any specific validation? I'm doing none, since I don't think that buchu should validate if this is an entity or something like that. But it's a requisit that the type inputed has a constructor.

**Comment by dalssoft** [comment]
looks great!

it seems you implemented / suggested both features:
1. `ignoreIDs`
2. `ignore` fields

which is more than fine to me

**Comment by maikvortx** [comment]
Hi guys! Make sense put a field that indicates whether realize a validation in schema or not?

**Comment by dalssoft** [comment]
> Make sense put a field that indicates whether realize a validation in schema or not?

To make it clear, you are suggesting to inherit the validation from a entity to the request, right?

Ex: a field with `presence: true` ona entity would produce a request with the same validation.

Is that correct?

**Comment by maikvortx** [comment]
My suggestion is to disable entity validation when a option is set to false in request. Example:

`Request.from(Entity, { useValidation: false })`

With this option a entity not valid will make a request to usecase. 

Make sense?

**Comment by VictorTBX** [comment]
> looks great!
> 
> it seems you implemented / suggested both features:
> 
> 1. `ignoreIDs`
> 2. `ignore` fields
> 
> which is more than fine to me

`ignoreIDs` or `ignoreID` ?

For me would be clearer to remove just the id from the main entity, not all of them.

**Comment by dalssoft** [comment]
`ignoreIDs` is better since an entity can have multiple ids fields (like a composite primary key to DB).

**Comment by VictorTBX** [comment]
https://github.com/herbsjs/buchu/pull/78

I'll create a PR for the documentation as soon as the review above is completed.

**Comment by dalssoft** [comment]
Great! PR merged. Waiting for PR with the docs.

**Comment by VictorTBX** [comment]
PR for the site doc:

https://github.com/herbsjs/herbsjs.github.io/pull/134

**Comment by VictorTBX** [comment]
I also added it to herbs library as exports
https://github.com/herbsjs/herbs/pull/39
