### ISSUE TITLE
Audit should record the input request

### ISSUE THREAD

**Issue by VictorTBX** [herbsjs/buchu#56]
The audit of an usecase should record the input request as an object itself. This allows more traceability of the requests, since the only information provided is the transactionId.

**Comment by jhomarolo** [comment]
@VictorTBX can you give an example of expected output?

**Comment by VictorTBX** [comment]
@jhomarolo sure do!

The example below has the `request` property.

```js
{
  type: 'use case',
  description: 'Test Stop',
  transactionId: 'bb768369-a6f6-4e9d-b081-f6c6ecf939ea',
  request: { id: 1 },
  return: { Ok: 'step1' },
  steps: [
    {
      type: 'step',
      description: 'Step1',
      return: [Object],
      elapsedTime: 26622000n,
      stopped: true
    }
  ],
  elapsedTime: 26818100n
}
```

I believe that this should be add before the validation of the request in usecase.js, something like this:
![image](https://user-images.githubusercontent.com/4419301/147384313-00ec3f04-4b62-4465-b137-d76bb4f4dc64.png)

This way, if something goes wrong with the schema and request validation, we still have the information.

**Comment by jhomarolo** [comment]
Thank you for your explanation @VictorTBX.

I'll put this issue as #ready-to-work, but feel free to change to wip if you wanna implement this request.

**Comment by VictorTBX** [comment]
@jhomarolo could add this one as work in progress, please?
