### ISSUE TITLE
request.from ignoreIDs

### ISSUE THREAD

**Issue by vitorgamer58** [herbsjs/buchu#83]
When I call request.from passing true in the "ignoreIDs" property, shouldn't it delete all IDs?

https://github.com/herbsjs/buchu/blob/master/src/request.js#L15

Because I'm dealing with a postgres, in which the transaction has two IDs, its own, and the ID of the account it is related to ("acc_id"), but in herbsshelf it showed the acc_id in the request.

![Screenshot_7008](https://user-images.githubusercontent.com/8906065/183316047-1ca5fde2-e959-4418-b057-3cfb29a97226.png)

**Comment by dalssoft** [comment]
Could you please share the definition of your entity?

**Comment by vitorgamer58** [comment]
> Could you please share the definition of your entity?

Of course

```
const Transaction =
  entity('Transaction', {
    id: id(String),
    description: field(String, { validation: { presence: true } }),
    type: field(Number, { validation: { presence: true } }),
    date: field(Date, { validation: { presence: true } }),
    amount: field(Number, { validation: { presence: true } }),
    status: field(Boolean, { validation: { presence: true } }),
    acc_id: id(String)
  })

module.exports =
  herbarium.entities
    .add(Transaction, 'Transaction')
    .entity
```

**Comment by dalssoft** [comment]
it is a bug. it should remove all fields defined as id(), not the "id" field.

**Comment by vitorgamer58** [comment]
But is there any scenario where the entity needs two id fields? Maybe it's more of a good practice than a bug, because it could be replaced by a field.

Because one of the issues is that I don't know if it's correct for an entity to have two ids, although in the database, it will be saved with an id of its own, and an id of the related account.

**Comment by dalssoft** [comment]
I would say it is a good practice to have just one id, however, Herbs should be agnostic about and support more than one id per entity.

**Comment by jairodiasvortx** [comment]
I wanna take this issue, can you tag for me @jhomarolo ?

**Comment by jairodiasvortx** [comment]
This point was resolved in september by another developer, it is attached


![Image](https://user-images.githubusercontent.com/122401562/219207416-9d28f336-a7ec-4a2b-8b2e-9bb2dc130a06.png)

**Comment by dalssoft** [comment]
@jairodiasvortx , can you send the PR or the test case implementation as a aditional evidence for closing this issue?

**Comment by jairodiasvortx** [comment]
@dalssoft, of course follow the link: https://github.com/herbsjs/buchu/commit/e13e1bd858afe38bee018d86bd70cbc19377f70a

**Comment by dalssoft** [comment]
thank you @jairodiasvortx . closing this issue
