### ISSUE TITLE
Improve exception throwing.

### ISSUE THREAD

**Issue by jhomarolo** [herbsjs/buchu#88]
**Is your feature request related to a problem? Please describe.**
Today some exceptions that happen inside the usecase are difficult to track because of the encapsulation that happens inside the step.

More info here: https://github.com/herbsjs/herbs/issues/22

**Comment by dalssoft** [comment]
Can we just keep one ticket (https://github.com/herbsjs/herbs/issues/22) for this issue?

Or even transfer the issue to this repo...

**Comment by dalssoft** [comment]
Since the issue is related to both entity and use case, I think is a good practice to leave the issue on the herbs repo.

**Comment by jhomarolo** [comment]
I'll close this issue and we continue inside the issue https://github.com/herbsjs/herbs/issues/22
